#!/usr/bin/env python

from timer_clients import countdown
import argparse, re, sys

def parse_args():
    ap = argparse.ArgumentParser(description='A simple count down timer')

    ap.add_argument('-w', '--weeks', default=0, type=int,
                    help='the number of weeks')
    ap.add_argument('-d', '--days', default=0, type=int,
                    help='the number of days')
    ap.add_argument('-o', '--hours', default=0, type=int,
                    help='the number of hours')
    ap.add_argument('-m', '--minutes', default=0, type=int,
                    help='the number of minutes')
    ap.add_argument('-s', '--seconds', default=0, type=int,
                    help='the number of seconds')

    return ap.parse_args()

def main():
    args = parse_args()

    timer = countdown.CountdownTimer(
        weeks=args.weeks,
        days=args.days,
        hours=args.hours,
        minutes=args.minutes,
        seconds=args.seconds
    )

    timer.execute()

if __name__ == "__main__":
    main()
