#!/usr/bin/env python

from timer_clients import countdown
import re, sys

def main():
    if len(sys.argv) <= 1:
        raise ValueError('invalid duration')

    regex = re.compile('^([0-9]+)(w|d|h|m|s)$', flags=re.IGNORECASE)
    weeks = 0
    days = 0
    hours = 0
    minutes = 0
    seconds = 0

    for option in sys.argv[1:]:
        match = regex.match(option)
        value = int(match.group(1))
        unit = str(match.group(2)).lower()

        if unit == 'w':
            self.weeks = value

        if unit == 'd':
            self.days = value

        if unit == 'h':
            self.hours = value

        if unit == 'm':
            self.minutes = value

        if unit == 's':
            seconds = value

    timer = countdown.CountdownTimer(weeks, days, hours, minutes, seconds)
    timer.execute()

if __name__ == "__main__":
    main()
